name: Build plugin

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip files
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Add to release
        run: ls -halt
